---
deployment:
  tasks:
    - export DEPLOYPATH=/home/printinv/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R serv $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R html $DEPLOYPATH
    - /bin/cp -R catalog $DEPLOYPATH
    - /bin/cp plotter-2138990_1920.webp $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R mark $DEPLOYPATH
